[discord]
token = ""

  [discord.users]
  mst = []

  [discord.role]
  digimon = ""

[guilds]
id = ""

[channels]
id = ""

# milliseconds
[timers]
reply_msg_lifespan = 10000
redraw_interval = 5000
notif_lifespan = 300000